version: '3.10'

services:
  cassandra:
    image: cassandra:4.0
    container_name: cassandra_db
    ports:
      - "9042:9042"
    env_file:
      - .env
    environment:
      - CASSANDRA_CLUSTER_NAME=MLCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_AUTHORIZER=CassandraAuthorizer
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "${CASSANDRA_USERNAME}", "-p", "${CASSANDRA_PASSWORD}", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

  ml-api:
    build: .
    container_name: ml-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      CASSANDRA_HOST: cassandra
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/active"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  cassandra_data:
