version: '3.10'

services:
  cassandra:
    image: cassandra:4.0
    container_name: cassandra_db
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MLCluster
      - CASSANDRA_DC=datacenter1
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5

  ml-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=ml_results
    depends_on:
      cassandra:
        condition: service_healthy
    restart: unless-stopped

volumes:
  cassandra_data: